enum NAVIGATION_TABS_NAME {
  HOME_TAB = "Home",
  LIBRARY_TAB = "Library",
  DISCOVER_TAB = "Discover",
  MORE_TAB = "More",
}

const NAVIGATION_ICON_NAME = {
  HOME_ICON: "home",
  LIBRARY_ICON: "library",
  DISCOVER_ICON: "discover",
  MORE_ICON: "more",
};
const ICON_SIZE = 25;
const TAB_BAR_HEIGHT = 70;
const CIRCLE_CONTAINER_SIZE = 16;
const NUM_TABS = 5;
const SCALE = 0.4;

export {
  NAVIGATION_TABS_NAME,
  NAVIGATION_ICON_NAME,
  ICON_SIZE,
  TAB_BAR_HEIGHT,
  CIRCLE_CONTAINER_SIZE,
  NUM_TABS,
  SCALE,
};
