import { Dimensions } from "react-native";

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get("window");
const SMALL_SCREEN_WIDTH = 375;
const LARGE_SCREEN_WIDTH = 390;
const X_LARGE_SCREEN_WIDTH = 430;
const X_LARGE_SCREEN_HEIGHT = 932;
const SMALL_BACKGROUND_WIDTH = 380;
const LARGE_BACKGROUND_WIDTH = 480;
const X_LARGE_BACKGROUND_WIDTH = 530;
const BACKGROUND_HEIGHT_RATIO = 2.59;

export {
  SCREEN_WIDTH,
  SCREEN_HEIGHT,
  SMALL_SCREEN_WIDTH,
  X_LARGE_SCREEN_WIDTH,
  LARGE_BACKGROUND_WIDTH,
  SMALL_BACKGROUND_WIDTH,
  X_LARGE_BACKGROUND_WIDTH,
  BACKGROUND_HEIGHT_RATIO,
  LARGE_SCREEN_WIDTH,
  X_LARGE_SCREEN_HEIGHT,
};
